version: "3"
services:
  strapi:
    build: .
    container_name: strapi_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "1337:1337"
    volumes:
      - .:/app # Mounts the whole project
      - /app/node_modules #
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: strapi_db
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
